---
title: "Tasks"
author: "Ruzza Tomas"
date: "6/24/2021"
output: pdf_document
---
RQ: Does strength of anti-covid measures (limitation of personal freedom of movement) depends on political position of national governments. 

h0=it does not depends from political scales but only from control factors
hA=it depends from the political scales.

control for:
-majority strength (OK)
-economic health (OK, used percentage of debit on pil, data from indexmundi)
-health system performance (OK, ICU data OCSE)
-epidemical situation(incidence of the virus. OK. data from our world in data, complete and filtered dataset)

Cercare dataset:
-Stringency_Index for the three covid 19 waves --> (OK)

-Left-right scale, Autorit-Libert, State-Market: operazionalization; Gov's strength (OK)

EconomicDataset (indexmundi, OK)

CovidData --> our world in data (OK)

Operazionalizations:
A. Scales:
   1. parlgov
   2. Chapell Hill: https://www.chesdata.eu --->controllo partiti

   
Stati da comporare: 25 ue

REPORT

-Introduction-->literature review
-research design -->spiego tutte le scelte e le operazionalizzazioni
-parte descrittiva --> grafico panel di stringency index (moving average?), distribuzione di incidenza virus(medie), tabella di scale politiche dei vari governi, grafico del debito, numero icu, maggioranze di governo
-modello runnato cross sectional-->no significance, alcune tabelle con simulation
-appendix: panel data approach (Pooled OLS)
-Discussions and limitations

